// experiences.js
export const experiences = [
  {
    id: 1,
    role: "PHP Developer",
    company: "SRV InfoTech",
    period: "June 2025 - Present",
    location: "Kannur, Kerala",
    type: "Full-time",
    logo: "/company_logos/srv_infotech.jfif",
    color: "#1DA1F2",
    points: [
      "Building modular CMS applications in Laravel with a focus on scalability and maintainability.",
      "Implemented repository-service architecture and refactored legacy CodeIgniter modules to improve stability and code structure",
      " Integrated Razorpay payment gateway with secure payment verification and webhook handling for reliable transactions.",
    ],
    technologies: [
      "Laravel",
      "CodeIgniter",
      "MySQL",
      "PHP",
      "AJAX",
      "jQuery",
      "JavaScript",
      "Razorpay",
      "Bootstrap",
      "CSS3",
      "HTML5",
      "cPanel",
    ],
  },
  {
    id: 2,
    role: "PHP Developer",
    company: "Weamse Business Solutions",
    period: "August 2024 - April 2025",
    location: "Kannur, Kerala",
    type: "Full-time",
    logo: "/company_logos/weamse.jfif",
    color: "#F7981F",
    points: [
      "Built 30+ RESTful API endpoints using Laravel and CodeIgniterto support scalable business workflows",
      "Integrated APIs with React using JWT-based authentication for secure frontend-backend communication.",
      "Applied Repository-Service pattern and SOLID principles to build modular and maintainable systems.",
      "Implemented asynchronous processing using Laravel Queues and scheduled commands for background automation.",
      "Integrated Stripe payment gateway with secure webhook validation and idempotent processing,reducing failed transactions by 20%.",
      "Led development of 3+ API and full-stack projects, increasing feature adoption by 40% and improving workflow efficiency by 35%.",
      "Optimized MySQL queries using indexing and eagerloading to reduce latency and eliminate N+1 issues.",
    ],
    technologies: [
      "Laravel",
      "CodeIgniter",
      "REST APIs",
      "jQuery",
      "JavaScript",
      "AJAX",
      "Bootstrap",
      "MySQL",
      "PHP",
      "API Development",
      "API Integration",
      "Payment Gateways",
      "Stripe",
      "React",
      "Git",
      "CSS3",
      "HTML5",
    ],
  },
  {
    id: 3,
    role: "PHP Developer",
    company: "NETPLEX",
    period: "April 2022 - July 2024",
    location: "Kannur, Kerala",
    type: "Full-time",
    logo: "/company_logos/NETPLEX.jfif",
    color: "#2E6862",
    points: [
      "Worked on and maintained web applications using PHP, Laravel, and CodeIgniter across billing and recharge systems.",
      "Engineered core features forrecharge and billing modules, improving operational efficiency and user satisfaction.",
      "Enhanced project functionality by 90% through new feature implementation and structured module maintenance.",
      "Resolved 80% of critical production issues, improving system stability and application performance.",
    ],
    technologies: [
      "Laravel",
      "CodeIgniter",
      "jQuery",
      "JavaScript",
      "AJAX",
      "Bootstrap",
      "MySQL",
      "PHP",
      "CSS3",
      "HTML5",
      "cPanel",
    ],
  },
  {
    id: 4,
    role: "Junior Application Developer",
    company: "Kiebot",
    period: "March 2021 - June 2021",
    location: "Kannur, Kerala",
    type: "Internship",
    logo: "/company_logos/kiebot.jfif",
    color: "#00235D",
    points: [
      "Contributed to the development of e-commerce application features using React Native.",
      "Assisted in the implementation of application features as part of MCA project.",
    ],
    technologies: ["React", "React Native"],
  },
];
