// experiences.js
export const experiences = [
  {
    id: 1,
    role: "PHP Developer",
    company: "Weamse Business Solutions",
    period: "August 2024 - April 2025",
    location: "Kannur, Kerala",
    type: "Full-time",
    logo: "/My-Portfolio/company_logos/weamse.jfif",
    color: "#F7981F",
    points: [
      "Built 30+ RESTful APIs using Laravel and CodeIgniter, ensuring seamless data exchange and scalability.",
      "Integrated backend APIs with React (JWT), contributing to frontend-backend connectivity using basic React knowledge.",
      "Followed Repository-Service pattern and SOLID principles to build maintainable codebases. And also automated background processes using Laravel Queues and Commands.",
      "Configured Stripe Payments with webhook validation,reducing failed transactions by 20%.",
      "Led development of 3+ API and full stack projects, increasing feature adoption by 40% and improving workflow efficiency by 35%.",
      "Optimized database queries and executed performance improvements to reduce latency",
    ],
    technologies: [
      "Laravel",
      "CodeIgniter",
      "REST APIs",
      "jQuery",
      "JavaScript",
      "AJAX",
      "Bootstrap",
      "MySQL",
      "PHP",
      "API Development",
      "API Integration",
      "Payment Gateways",
      "Stripe",
      "React",
      "Git",
      "CSS3",
      "HTML5",
    ],
  },
  {
    id: 2,
    role: "PHP Developer",
    company: "NETPLEX",
    period: "April 2022 - July 2024",
    location: "Kannur, Kerala",
    type: "Full-time",
    logo: "/My-Portfolio/company_logos/NETPLEX.jfif",
    color: "#2E6862",
    points: [
      "Developed and elevated web applications using PHP, Laravel, and CodeIgniter, enhancing both front-end and back-end functionality forimproved user experience.",
      "Engineered key features forrecharge and billing applications, boosting productivity and customer satisfaction.",
      "Increased project functionality by 90% by implementing new features and maintaining existing modules.",
      "Resolved 80% of critical bugs, improving application performance, stability, and overall product growth.",
      "Gained hands-on experience in API development and management.",
    ],
    technologies: [
      "Laravel",
      "CodeIgniter",
      "jQuery",
      "JavaScript",
      "AJAX",
      "Bootstrap",
      "MySQL",
      "PHP",
      "CSS3",
      "HTML5",
      "cPanel",
    ],
  },
  {
    id: 3,
    role: "Junior Application Developer",
    company: "Kiebot",
    period: "March 2021 - June 2021",
    location: "Kannur, Kerala",
    type: "Internship",
    logo: "/My-Portfolio/company_logos/kiebot.jfif",
    color: "#00235D",
    points: [
      "Contributed to the development of e-commerce application features using React Native.",
      "Assisted in the implementation of application features as part of MCA project.",
    ],
    technologies: ["React", "React Native"],
  },
];
