export const projects = [
  {
    id: 1,
    title: "Multi-Vendor eCommerce Platform",
    subtitle: "Laravel + React JS + Inertia JS",
    tagline: "Pitch. Browse. Engage.",
    slug: "multi-vendor-ecommerce",
    description:
      "A modern full stack Multi-Vendor eCommerce Website using Laravel, React JS, Inertia JS, Typescript and Tailwind CSS with advanced features.",
    keyFeatures: [
      "Multi-Vendor eCommerce System with admin & vendor panels",
      "Laravel backend with clean architecture using Services",
      "Stripe Integration, Order Management, Spatie Media Library",
      "Built with React, Tailwind CSS, Inertia, Typescript",
    ],
    shortDescription:
      "A powerful marketplace platform enabling multiple vendors to sell, manage, and grow their business online.",
    longDescription:
      "This project represents a complete overhaul of traditional eCommerce systems, incorporating modern development practices and cutting-edge technologies. The platform serves as a marketplace where multiple vendors can register, manage their products, and process orders while administrators maintain full control over the system. Built with scalability in mind, it handles complex vendor relationships, commission structures, and multi-tier user management.",
    keyDetailedFeatures: [
      "Multi-Vendor eCommerce System with comprehensive admin & vendor panels",
      "Laravel backend with clean architecture using Service pattern",
      "Stripe Integration for secure payments and subscription management",
      "Advanced Order Management with real-time tracking and notifications",
      "Spatie Media Library for efficient file and image management",
      "Built with React, Tailwind CSS, Inertia, and TypeScript for type safety",
      "Role-based access control with granular permissions",
      "Real-time dashboard analytics and reporting system",
    ],
    technicalHighlights: [
      "Used Service Layer for business logic separation",
      "Implemented Queue system for background job processing",
    ],
    challenges: [
      "Complex vendor commission calculation system",
      "Inventory management across multiple vendors",
      "Implementing secure payment processing with stripe",
    ],
    tagsDescription:
      "A production-grade application showcasing modern development practices, clean architecture, and cutting-edge technologies. Built with performance, scalability, and user experience as core priorities.",
    themeColor: "#9334EA",
    colorStart: "#301B55",
    colorEnd: "#7326B8",
    image: "/My-Portfolio/projects/Laravel-React-Ecommerce.png",
    tags: [
      "Laravel",
      "React JS",
      "Inertia JS",
      "Typescript",
      "Tailwind CSS",
      "Filament",
      "Stripe",
      "Spatie Media Library",
    ],
    demoURL: "",
    gitHubURL: "https://github.com/Archanaub04/Laravel-React-E-Commerce",
    status: "Development",
    featured: true,
    startDate: "2024-01-15",
    category: "Full-Stack Development",
    client: "Internal Project",
  },
  {
    id: 2,
    title: "Archana's Portfolio",
    subtitle: "Personal Portfolio Website",
    tagline: "Pitch. Browse. Engage.",
    slug: "my-portfolio",
    description:
      "A beautiful modern portfolio with space theme using React JS and Tailwind CSS, featuring smooth animations and responsive design.",
    keyFeatures: [
      "Modern space-themed design using React, Tailwind & Framer Motion",
      "Custom animation with star background, meteors, dark/light mode",
      "Responsive, accessible, optimized for performance",
    ],
    shortDescription:
      "A space-inspired animated portfolio built to showcase my skills, projects, and personality with flair.",
    longDescription:
      "A personal developer portfolio website with a modern and immersive space-themed interface. Designed to highlight my technical projects, skills, and contact information. Developed using React, Tailwind CSS, and Framer Motion, the UI focuses on smooth transitions, visual storytelling, and minimalistic layouts to create a memorable user experience.",
    keyDetailedFeatures: [
      "Custom animated space theme with meteor effects",
      "Responsive layout for all devices (mobile/tablet/desktop)",
      "Framer Motion for elegant animations and transitions",
      "Dark/Light theme toggle functionality",
      "Clean project card layout and skills filtering support",
      // "SEO optimized with clean URL slugs and meta tags",
    ],
    technicalHighlights: [
      "Used React functional components with hooks",
      "Deployed via GitHub Pages for fast CDN delivery",
    ],
    challenges: [
      "Ensuring visual consistency across dark/light themes",
      "Optimizing animation performance for low-end devices",
    ],
    tagsDescription:
      "A minimal yet creative personal portfolio to present work, skills, and experience with an interactive and responsive design.",
    themeColor: "#805ad5",
    colorStart: "#0f172a",
    colorEnd: "#312e81",
    image: "/My-Portfolio/projects/my-portfolio.png",
    tags: ["React JS", "Tailwind CSS", "Vite", "Framer Motion"],
    demoURL: "https://archanaub04.github.io/My-Portfolio/",
    gitHubURL: "https://github.com/Archanaub04/My-Portfolio",
    status: "Completed",
    featured: true,
    startDate: "2024-01-15",
    category: "Frontend Development",
    client: "Internal Project",
  },
  {
    id: 3,
    title: "E-Commerce Platform",
    subtitle: "",
    tagline: "Pitch. Browse. Engage.",
    slug: "ecommerce-platform",
    description:
      "A fully dynamic Single Vendor E-Commerce Website using Laravel and React JS. Developed full API and integrated RTK Query for frontend state management.",
    keyFeatures: [
      "Built complete API with Laravel & JWT Authentication",
      "RTK Query for efficient data fetching and caching",
      "Stripe integration, Cart & Order logic, Admin Panel",
    ],
    shortDescription:
      "A complete single-vendor eCommerce solution with seamless checkout, admin control, and secure payments.",
    longDescription:
      "An end-to-end eCommerce platform designed for a single vendor, offering a seamless shopping experience. Backend built in Laravel with clean architecture using services and repository pattern. The frontend uses React and Redux Toolkit (RTK Query) for scalable state management, enabling real-time cart, order, and product data interactions.",
    keyDetailedFeatures: [
      "Single-vendor shop with fully functional cart & checkout",
      "Laravel RESTful API with JWT token-based authentication",
      "Clean architecture using Service & Repository pattern",
      "Stripe integration for secure payments",
      "Admin Panel to manage orders, products & users",
      "RTK Query for scalable frontend state management",
    ],
    technicalHighlights: [
      "Implemented Repository Pattern for data abstraction",
      "JWT for secure API authentication",
      "React + RTK Query for optimal frontend data handling",
    ],
    challenges: [
      "Handling edge cases in cart & checkout flow",
      "Integrating secure multi-step checkout with Stripe",
      "Product variation management with dynamic stock control",
    ],
    tagsDescription:
      "A fast and scalable e-commerce system tailored for a single vendor, focused on performance, clean architecture, and modern frontend integration.",
    themeColor: "#4D122B",
    colorStart: "#4D122B",
    colorEnd: "#831843",
    image: "/My-Portfolio/projects/weamse_ecom.png",
    tags: ["Laravel", "REST APIs", "React JS", "Stripe", "JWT"],
    demoURL: "https://ecom.weamse.org/",
    gitHubURL: "",
    status: "Development",
    featured: true,
    startDate: "2024-01-15",
    category: "Backend Development",
    client: "Internal Project",
  },
];
